# Generated by Django 5.2.7 on 2025-10-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
        migrations.AddField(
            model_name='route',
            name='position',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination'), ('source', 'position')},
        ),
    ]
